In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import gc
import sys
import os
sys.path.append('./autoimmuneSC/')
#from AIID_notebooks.inflapy.immunoFunc import *

##### braga_asthma

In [2]:
print(sc.__version__)

1.9.1

In [3]:
path="/lustre/scratch117/cellgen/cellgeni/TIC-starsolo/tic-1808/Felipe_SS2/Felipe.solo.SS2/"

In [4]:
s_path = "/nfs/team205/bh14/Datasets/Remapped/raw_adata/"

In [5]:
adata = sc.read_10x_mtx(path+"output/Gene/filtered/")

In [6]:
adata.obs_names

Index(['Run20956_lane1_3', 'Run20956_lane1_7', 'Run20956_lane1_21',
       'Run20956_lane1_23', 'Run20956_lane1_61', 'Run20956_lane1_69',
       'Run20956_lane1_71', 'Run20956_lane1_97', 'Run20956_lane1_119',
       'Run20956_lane1_149',
       ...
       'Run24618_lane4_219', 'Run22219_lanes23_221', 'Run22219_lanes23_333',
       'Run24028_lane5_275', 'Run24028_lane8_37', 'Run24028_lane8_319',
       'Run24028_lane8_342', 'Run24028_lane8_352', 'Run24618_lane2_213',
       'Run21843_lane4_144'],
      dtype='object', length=2637)

In [28]:
#GSE121380/GSM3433578/output/Velocyto/filtered/

pheno = pd.read_csv(s_path+"Braga_data/pheno_CD4.csv", index_col=0)

In [29]:
pheno.head()

                   disease donor_id tissue        dataset_id cell_source
Run20956_lane1_3   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_7   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_21  Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_23  Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_61  Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4

In [15]:
#pheno.drop_duplicates(inplace=True, ignore_index=True)

In [32]:
pheno_blood = pheno[pheno.tissue == "Blood"]

In [33]:
#pheno_blood.reset_index(inplace=True, drop=True)
pheno_blood

                    disease donor_id tissue        dataset_id cell_source
Run20956_lane1_3    Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_7    Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_21   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_23   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_61   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
...                     ...      ...    ...               ...         ...
Run23847_lane8_221   Asthma  ARMS015  Blood  Braga_asthma_CD4   Blood_CD4
Run23847_lane8_227   Asthma  ARMS015  Blood  Braga_asthma_CD4   Blood_CD4
Run23847_lane8_255   Asthma  ARMS015  Blood  Braga_asthma_CD4   Blood_CD4
Run24028_lane7_342   Asthma  ARMS035  Blood  Braga_asthma_CD4   Blood_CD4
Run24028_lane7_371   Asthma  ARMS035  Blood  Braga_asthma_CD4   Blood_CD4

[992 rows x 5 columns]

In [34]:
pheno_lung = pheno[pheno.tissue == "Lung"]
#pheno_lung.reset_index(inplace=True, drop=True)

In [35]:
pheno_lung

                    disease donor_id tissue        dataset_id cell_source
Run20956_lane1_254  Healthy  ARMS005   Lung  Braga_asthma_CD4    Lung_CD4
Run20956_lane7_22   Healthy  ARMS005   Lung  Braga_asthma_CD4    Lung_CD4
Run21833_lane2_7    Healthy  ARMS004   Lung  Braga_asthma_CD4    Lung_CD4
Run21833_lane2_21   Healthy  ARMS004   Lung  Braga_asthma_CD4    Lung_CD4
Run21833_lane2_23   Healthy  ARMS004   Lung  Braga_asthma_CD4    Lung_CD4
...                     ...      ...    ...               ...         ...
Run24028_lane8_319   Asthma  ARMS033   Lung  Braga_asthma_CD4    Lung_CD4
Run24028_lane8_342   Asthma  ARMS033   Lung  Braga_asthma_CD4    Lung_CD4
Run24028_lane8_352   Asthma  ARMS033   Lung  Braga_asthma_CD4    Lung_CD4
Run24618_lane2_213   Asthma  ARMS033   Lung  Braga_asthma_CD4    Lung_CD4
Run21843_lane4_144  Healthy  ARMS004   Lung  Braga_asthma_CD4    Lung_CD4

[1942 rows x 5 columns]

##### Immune compartment

In [37]:
imm = adata[adata.obs_names.isin(pheno_blood.index)]

In [38]:
imm

View of AnnData object with n_obs × n_vars = 929 × 36601
    var: 'gene_ids', 'feature_types'

In [46]:
pheno_blood = pheno_blood[pheno_blood.index.isin(imm.obs.index)]

In [47]:
pheno_blood

                    disease donor_id tissue        dataset_id cell_source
Run20956_lane1_3    Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_7    Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_21   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_23   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_61   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
...                     ...      ...    ...               ...         ...
Run23847_lane8_221   Asthma  ARMS015  Blood  Braga_asthma_CD4   Blood_CD4
Run23847_lane8_227   Asthma  ARMS015  Blood  Braga_asthma_CD4   Blood_CD4
Run23847_lane8_255   Asthma  ARMS015  Blood  Braga_asthma_CD4   Blood_CD4
Run24028_lane7_342   Asthma  ARMS035  Blood  Braga_asthma_CD4   Blood_CD4
Run24028_lane7_371   Asthma  ARMS035  Blood  Braga_asthma_CD4   Blood_CD4

[929 rows x 5 columns]

In [48]:
imm.obs = pheno_blood

In [49]:
imm.obs

                    disease donor_id tissue        dataset_id cell_source
Run20956_lane1_3    Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_7    Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_21   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_23   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
Run20956_lane1_61   Healthy  ARMS005  Blood  Braga_asthma_CD4   Blood_CD4
...                     ...      ...    ...               ...         ...
Run23847_lane8_221   Asthma  ARMS015  Blood  Braga_asthma_CD4   Blood_CD4
Run23847_lane8_227   Asthma  ARMS015  Blood  Braga_asthma_CD4   Blood_CD4
Run23847_lane8_255   Asthma  ARMS015  Blood  Braga_asthma_CD4   Blood_CD4
Run24028_lane7_342   Asthma  ARMS035  Blood  Braga_asthma_CD4   Blood_CD4
Run24028_lane7_371   Asthma  ARMS035  Blood  Braga_asthma_CD4   Blood_CD4

[929 rows x 5 columns]

In [50]:
imm.write_h5ad(s_path+"Immune_compartment/Braga_asthma_blood_CD4.h5ad")

/home/jovyan/my-conda-envs/autoimmune/lib/python3.8/site-packages/anndata/_core/anndata.py:1235: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[key] = c

In [51]:
imm.obs["disease"].value_counts()

Healthy    573
Asthma     356
Name: disease, dtype: int64

In [52]:
sorted_imm = adata[adata.obs_names.isin(pheno_lung.index)]

In [53]:
sorted_imm

View of AnnData object with n_obs × n_vars = 1708 × 36601
    var: 'gene_ids', 'feature_types'

In [54]:
pheno_lung = pheno_lung[pheno_lung.index.isin(sorted_imm.obs.index)]

In [55]:
pheno_lung.head()

                    disease donor_id tissue        dataset_id cell_source
Run20956_lane1_254  Healthy  ARMS005   Lung  Braga_asthma_CD4    Lung_CD4
Run20956_lane7_22   Healthy  ARMS005   Lung  Braga_asthma_CD4    Lung_CD4
Run21833_lane2_7    Healthy  ARMS004   Lung  Braga_asthma_CD4    Lung_CD4
Run21833_lane2_21   Healthy  ARMS004   Lung  Braga_asthma_CD4    Lung_CD4
Run21833_lane2_23   Healthy  ARMS004   Lung  Braga_asthma_CD4    Lung_CD4

In [56]:
sorted_imm.obs = pheno_lung

In [57]:
sorted_imm.write_h5ad(s_path+"Immune_compartment_sorted_from_Tissue/Braga_asthma_lung_CD4.h5ad")

/home/jovyan/my-conda-envs/autoimmune/lib/python3.8/site-packages/anndata/_core/anndata.py:1235: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[key] = c

### Lung asthma

In [5]:
path="/lustre/scratch127/cellgen/cellgeni/tickets/tic-1808/Sanger_samples/"

In [6]:
s_path = "/nfs/team205/bh14/Datasets/Remapped/raw_adata/"

In [8]:
#"CTTV027_RNAseq7487979_CTTV027_RNAseq7487979" "CTTV027_RNAseq7333559"                       "CTTV027_RNAseq7333558_CTTV027_RNAseq7333558"
#[4] "CTTV027_RNAseq6949175"                       "CTTV027_RNAseq7018935"                       "CTTV027_RNAseq7018936"

In [9]:
sample = {"CTTV027_RNAseq6949177":"Healthy", 
          "CTTV027_RNAseq7487979":"Asthma", 
          "CTTV027_RNAseq7333559":"Asthma", 
          "4951STDY7487591":"Healthy",
          "CTTV027_RNAseq7118946":"Healthy", 
          "CTTV027_RNAseq7333558":"Asthma", 
          "CTTV027_RNAseq6949176":"Healthy", 
          "CTTV027_RNAseq7118945":"Healthy", 
          "CTTV027_RNAseq7333557":"Healthy", 
          "CTTV027_RNAseq6949175":"Asthma", 
          "CTTV027_RNAseq7018935":"Asthma", 
          "CTTV027_RNAseq7018936":"Asthma"}

In [10]:
sample.values()

dict_values(['Healthy', 'Asthma', 'Asthma', 'Healthy', 'Healthy', 'Asthma', 'Healthy', 'Healthy', 'Healthy', 'Asthma', 'Asthma', 'Asthma'])

In [10]:
#samp = sc.read_10x_mtx(path+sample[0]+"/output/Gene/filtered/")

In [12]:
#samp.obs_names

Index(['AAACCTGAGATGCCTT', 'AAACCTGAGATGTCGG', 'AAACCTGAGCTTCGCG',
       'AAACCTGAGGGTCTCC', 'AAACCTGAGGTGCTAG', 'AAACCTGCAGCAGTTT',
       'AAACCTGCATTAACCG', 'AAACCTGGTACGAAAT', 'AAACCTGGTAGCAAAT',
       'AAACCTGGTGTTGAGG',
       ...
       'TTTGTCACAATAGCAA', 'TTTGTCACACCTCGTT', 'TTTGTCACACGGCCAT',
       'TTTGTCACACGGTAGA', 'TTTGTCACAGGACCCT', 'TTTGTCACATTCGACA',
       'TTTGTCAGTACCGTTA', 'TTTGTCAGTGGTTTCA', 'TTTGTCAGTGTAATGA',
       'TTTGTCATCTTAGAGC'],
      dtype='object', length=6480)

In [15]:
#del adata_conc

gc.collect()

15389

In [16]:
for samp in sample.keys():
    
    print("Processing "+samp)
    adata = sc.read_10x_mtx(path+samp+"/output/Gene/filtered/")

    #adata.var[['ensembl', 'gene_symbol']]
    
    adata.obs["dataset_id"] = "Braga_asthma"
    adata.obs["donor_id"] = samp
    adata.obs["tissue"] = "lung"
    adata.obs["cell_source"] = np.nan
    adata.obs["disease"] = "Asthma" #Wrong label. Will be correct during label transfert
    adata.obs["disease_status"] = np.nan
    adata.obs["age"] = np.nan
    adata.obs["sex"] = np.nan
    adata.obs["developmental_stage"] = np.nan
    adata.obs["sample_id"] = adata.obs_names
    if 'adata_conc' in locals():
        adata.var_names_make_unique()
        adata_conc.var_names_make_unique()
        adata_conc = sc.concat([adata,adata_conc], index_unique="-")
        
    else:
        adata_conc = adata

    print(adata_conc.shape)

Processing CTTV027_RNAseq6949177
(6480, 36601)
Processing CTTV027_RNAseq7487979
(20325, 36601)
Processing CTTV027_RNAseq7333559
(49840, 36601)
Processing 4951STDY7487591
(62530, 36601)
Processing CTTV027_RNAseq7118946
(66618, 36601)
Processing CTTV027_RNAseq7333558
(75924, 36601)
Processing CTTV027_RNAseq6949176
(80037, 36601)
Processing CTTV027_RNAseq7118945
(84402, 36601)
Processing CTTV027_RNAseq7333557
(98625, 36601)
Processing CTTV027_RNAseq6949175
(102466, 36601)
Processing CTTV027_RNAseq7018935
(106888, 36601)
Processing CTTV027_RNAseq7018936
(116638, 36601)

In [17]:
adata_conc.obs_names

Index(['AAACCTGAGAGCAATT-0', 'AAACCTGAGCTAAACA-0', 'AAACCTGCACACGCTG-0',
       'AAACCTGCACCGATAT-0', 'AAACCTGCACGGATAG-0', 'AAACCTGCACGGTAAG-0',
       'AAACCTGCATCACGAT-0', 'AAACCTGGTAAACGCG-0', 'AAACCTGGTACCGGCT-0',
       'AAACCTGGTAGCCTCG-0',
       ...
       'TTTGTCACAATAGCAA-1-1-1-1-1-1-1-1-1-1-1',
       'TTTGTCACACCTCGTT-1-1-1-1-1-1-1-1-1-1-1',
       'TTTGTCACACGGCCAT-1-1-1-1-1-1-1-1-1-1-1',
       'TTTGTCACACGGTAGA-1-1-1-1-1-1-1-1-1-1-1',
       'TTTGTCACAGGACCCT-1-1-1-1-1-1-1-1-1-1-1',
       'TTTGTCACATTCGACA-1-1-1-1-1-1-1-1-1-1-1',
       'TTTGTCAGTACCGTTA-1-1-1-1-1-1-1-1-1-1-1',
       'TTTGTCAGTGGTTTCA-1-1-1-1-1-1-1-1-1-1-1',
       'TTTGTCAGTGTAATGA-1-1-1-1-1-1-1-1-1-1-1',
       'TTTGTCATCTTAGAGC-1-1-1-1-1-1-1-1-1-1-1'],
      dtype='object', length=116638)

In [18]:
adata_conc.obs.sample_id

AAACCTGAGAGCAATT-0                        AAACCTGAGAGCAATT
AAACCTGAGCTAAACA-0                        AAACCTGAGCTAAACA
AAACCTGCACACGCTG-0                        AAACCTGCACACGCTG
AAACCTGCACCGATAT-0                        AAACCTGCACCGATAT
AAACCTGCACGGATAG-0                        AAACCTGCACGGATAG
                                                ...
TTTGTCACATTCGACA-1-1-1-1-1-1-1-1-1-1-1    TTTGTCACATTCGACA
TTTGTCAGTACCGTTA-1-1-1-1-1-1-1-1-1-1-1    TTTGTCAGTACCGTTA
TTTGTCAGTGGTTTCA-1-1-1-1-1-1-1-1-1-1-1    TTTGTCAGTGGTTTCA
TTTGTCAGTGTAATGA-1-1-1-1-1-1-1-1-1-1-1    TTTGTCAGTGTAATGA
TTTGTCATCTTAGAGC-1-1-1-1-1-1-1-1-1-1-1    TTTGTCATCTTAGAGC
Name: sample_id, Length: 116638, dtype: object

In [19]:
adata_conc.write_h5ad(s_path+"Tissue_or_Nonimmune/Braga_asthma_lung.h5ad")

In [24]:
meta = pd.read_csv("/lustre/scratch126/cellgen/team205/bh14/asthma/MetaasthmaAirwayLung_cells.txt", delimiter=" ")

In [25]:
meta

,tSNE_1,tSNE_2,clus,disease,dataset_id,tissue,donor_id
CTTV027_RNAseq6949177_CAGCTAACAGGTCGTC,-17.241983,5.087833,Activated endothelium,Healthy,braga_asthma_others,lung,CTTV027_RNAseq6949177
CTTV027_RNAseq7487979_CTTV027_RNAseq7487979CAACCTCAGCCAGTAG,-17.338519,12.340450,Endothelium,Asthma,braga_asthma_others,lung,CTTV027_RNAseq7487979_CTTV027_RNAseq7487979
CTTV027_RNAseq7333559TAGCCGGCATGGAATA,-25.377179,2.866250,Activated endothelium,Asthma,braga_asthma_others,lung,CTTV027_RNAseq7333559
4951STDY7487591CACACAACATAGACTC,-20.950459,1.507955,Activated endothelium,Healthy,braga_asthma_others,lung,4951STDY7487591
4951STDY7487591CGCGTTTGTTCGAATC,-15.734668,7.992287,Endothelium,Healthy,braga_asthma_others,lung,4951STDY7487591
...,...,...,...,...,...,...,...
CTTV027_RNAseq7333558_CTTV027_RNAseq7333558CCTTCGACAAATTGCC,-7.530124,-27.903879,Luminal macrophages,Asthma,braga_asthma_others,lung,CTTV027_RNAseq7333558_CTTV027_RNAseq7333558
CTTV027_RNAseq7333558_CTTV027_RNAseq7333558CGATCGGTCGCCAAAT,-8.607374,-29.359056,Luminal macrophages,Asthma,braga_asthma_others,lung,CTTV027_RNAseq7333558_CTTV027_RNAseq7333558
CTTV027_RNAseq7333558_CTTV027_RNAseq7333558GCGCCAATCTGCTGCT,-8.424184,-29.989269,Luminal macrophages,Asthma,braga_asthma_others,lung,CTTV027_RNAseq7333558_CTTV027_RNAseq7333558
CTTV027_RNAseq7333559AAGCCGCGTCGCTTCT,-9.439834,-29.938902,Luminal macrophages,Asthma,braga_asthma_others,lung,CTTV027_RNAseq7333559
CTTV027_RNAseq7333559GAAACTCAGTGTACGG,-7.489807,-27.694101,Luminal macrophages,Asthma,braga_asthma_others,lung,CTTV027_RNAseq7333559

In [ ]:
/nfs/team205/bh14/Datasets/Remapped/raw_adata/Tissue_or_Nonimmune/Braga_asthma_lung.h5ad