In [1]:
import numpy as np
import pandas as pd
import scanpy as sc
import gc
import sys
import os
sys.path.append('../')
from AIID_notebooks.inflapy.immunoFunc import *

##### SDY1599_Wei_2020

In [2]:
print(sc.__version__)

1.9.1

In [3]:
path="/lustre/scratch117/cellgen/cellgeni/TIC-starsolo/tic-1808/SDY1599/"

In [4]:
s_path = "/nfs/team205/bh14/Datasets/Remapped/raw_adata/SDY1599/"

In [5]:
#GSE121380/GSM3433578/output/Velocyto/filtered/
pheno = pd.read_table(s_path+"SDY1599-DR45_Subject_2_RNA_sequencing_result.txt")

pheno2 = pd.read_table(s_path+"immune_exposure.txt")

In [6]:
pheno

,Subject Accession,Species,Race,Race Specify,Ethnicity,Strain,Gender,Age Event,Age Event Specify,Subject Age,...,Expsample Description,Expsample Result Schema,Expsample Treatement,Reagent Accession,Reagent Name,Reagent Reporter Name,File Info ID,File Detail,File Name,Original File Name
0,SUB207729,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,749135,RNA sequencing result,RA1_S1_L001_R1_001.fastq.749135.gz,RA1_S1_L001_R1_001.fastq.gz
1,SUB207729,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,749136,RNA sequencing result,RA1_S1_L001_R2_001.fastq.749136.gz,RA1_S1_L001_R2_001.fastq.gz
2,SUB207729,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,749137,RNA sequencing result,RA1_S1_L002_R1_001.fastq.749137.gz,RA1_S1_L002_R1_001.fastq.gz
3,SUB207729,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,749138,RNA sequencing result,RA1_S1_L002_R2_001.fastq.749138.gz,RA1_S1_L002_R2_001.fastq.gz
4,SUB207729,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,749139,RNA sequencing result,RA1_S3_L001_R1_001.fastq.749139.gz,RA1_S3_L001_R1_001.fastq.gz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,SUB207742,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,744240,RNA sequencing result,MM2_S4_L004_R2_001.fastq.744240.gz,MM2_S4_L004_R2_001.fastq.gz
64,SUB207743,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,744241,RNA sequencing result,MM3_CDNA_S2_L001_R1_001.fastq.744241.gz,MM3_CDNA_S2_L001_R1_001.fastq.gz
65,SUB207743,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,744242,RNA sequencing result,MM3_CDNA_S2_L001_R2_001.fastq.744242.gz,MM3_CDNA_S2_L001_R2_001.fastq.gz
66,SUB207743,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,744243,RNA sequencing result,MM3_HTO_S1_L004_I1_001.fastq.744243.gz,MM3_HTO_S1_L004_I1_001.fastq.gz
67,SUB207743,Homo sapiens,Not Specified,NaN,Not Specified,NaN,Not Specified,Not Specified,NaN,21,...,NaN,RNA SEQ,no ex vivo treatment,ESR24535,"scRNAseq Chromium chip, 10X Genomics",NaN,744244,RNA sequencing result,MM3_HTO_S1_L004_R1_001.fastq.744244.gz,MM3_HTO_S1_L004_R1_001.fastq.gz

In [7]:
pheno.columns

Index(['Subject Accession', 'Species', 'Race', 'Race Specify', 'Ethnicity',
       'Strain', 'Gender', 'Age Event', 'Age Event Specify', 'Subject Age',
       'Age Unit', 'Subject Phenotype', 'ARM Accession', 'ARM Name',
       'Study Accession', 'Study Brief Title', 'Biosample Accession',
       'Biosample Description', 'Biosample Name', 'Biosample Type',
       'Biosample Subtype', 'Study Time Collected',
       'Study Time Collected Unit', 'Study Time T0 Event',
       'Study Time T0 Event Specify', 'Biosample Treatment',
       'Planned Visit Accession', 'Planned Visit Name', 'Experiment Accession',
       'Expsample Accession', 'Expsample Description',
       'Expsample Result Schema', 'Expsample Treatement', 'Reagent Accession',
       'Reagent Name', 'Reagent Reporter Name', 'File Info ID', 'File Detail',
       'File Name', 'Original File Name'],
      dtype='object')

In [8]:
pheno = pheno.loc[:,['Subject Accession', 'Subject Age', 'Gender',
       'ARM Name', 'Original File Name']]

In [9]:
pheno.head()

,Subject Accession,Subject Age,Gender,ARM Name,Original File Name
0,SUB207729,21,Not Specified,Synovial tissue,RA1_S1_L001_R1_001.fastq.gz
1,SUB207729,21,Not Specified,Synovial tissue,RA1_S1_L001_R2_001.fastq.gz
2,SUB207729,21,Not Specified,Synovial tissue,RA1_S1_L002_R1_001.fastq.gz
3,SUB207729,21,Not Specified,Synovial tissue,RA1_S1_L002_R2_001.fastq.gz
4,SUB207729,21,Not Specified,Synovial tissue,RA1_S3_L001_R1_001.fastq.gz

In [10]:
import re

In [11]:
pattern = re.compile("_S.*_L00.*fastq.gz$")

In [12]:
samples = [pattern.sub("", samp) for samp in pheno["Original File Name"]]

In [13]:
pheno["Original File Name"] = samples

In [14]:
pheno["ARM Name"].value_counts()

Synovial tissue      48
Synovial organoid    20
Name: ARM Name, dtype: int64

In [15]:
pheno.drop_duplicates(inplace=True, ignore_index=True)

In [16]:
pheno

,Subject Accession,Subject Age,Gender,ARM Name,Original File Name
0,SUB207729,21,Not Specified,Synovial tissue,RA1
1,SUB207730,21,Not Specified,Synovial tissue,RA2
2,SUB207731,21,Not Specified,Synovial tissue,RA3
3,SUB207732,21,Not Specified,Synovial tissue,RA4
4,SUB207733,21,Not Specified,Synovial tissue,RA5
5,SUB207734,21,Not Specified,Synovial tissue,RA6
6,SUB207741,21,Not Specified,Synovial organoid,MM1
7,SUB207742,21,Not Specified,Synovial organoid,MM2
8,SUB207743,21,Not Specified,Synovial organoid,MM3_CDNA
9,SUB207743,21,Not Specified,Synovial organoid,MM3_HTO

In [17]:
pheno.columns = ["sample_id", "age", "sex", "tissue", "donor_id"]

In [18]:
pheno.head()

   sample_id  age            sex           tissue donor_id
0  SUB207729   21  Not Specified  Synovial tissue      RA1
1  SUB207730   21  Not Specified  Synovial tissue      RA2
2  SUB207731   21  Not Specified  Synovial tissue      RA3
3  SUB207732   21  Not Specified  Synovial tissue      RA4
4  SUB207733   21  Not Specified  Synovial tissue      RA5

In [19]:
pheno2.head()

,EXPOSURE_ACCESSION,ARM_ACCESSION,DISEASE_ONTOLOGY_ID,DISEASE_PREFERRED,DISEASE_REPORTED,DISEASE_STAGE_PREFERRED,DISEASE_STAGE_REPORTED,EXPOSURE_MATERIAL_ID,EXPOSURE_MATERIAL_PREFERRED,EXPOSURE_MATERIAL_REPORTED,EXPOSURE_PROCESS_PREFERRED,EXPOSURE_PROCESS_REPORTED,SUBJECT_ACCESSION
0,IM18905,ARM5157,DOID:7148,rheumatoid arthritis,rheumatoid arthritis,Chronic,Chronic,NaN,NaN,NaN,occurrence of disease,occurrence of disease,SUB207729
1,IM18906,ARM5157,DOID:7148,rheumatoid arthritis,rheumatoid arthritis,Chronic,Chronic,NaN,NaN,NaN,occurrence of disease,occurrence of disease,SUB207730
2,IM18907,ARM5157,DOID:7148,rheumatoid arthritis,rheumatoid arthritis,Chronic,Chronic,NaN,NaN,NaN,occurrence of disease,occurrence of disease,SUB207731
3,IM18908,ARM5157,DOID:7148,rheumatoid arthritis,rheumatoid arthritis,Chronic,Chronic,NaN,NaN,NaN,occurrence of disease,occurrence of disease,SUB207732
4,IM18909,ARM5157,DOID:7148,rheumatoid arthritis,rheumatoid arthritis,Chronic,Chronic,NaN,NaN,NaN,occurrence of disease,occurrence of disease,SUB207733

In [20]:
#Maintain only primary tissue
pheno = pheno[pheno["tissue"] != "Synovial organoid"]

In [21]:
pheno2.DISEASE_PREFERRED.value_counts()

rheumatoid arthritis    18
osteoarthritis          14
Name: DISEASE_PREFERRED, dtype: int64

In [22]:
pheno2.columns

Index(['EXPOSURE_ACCESSION', 'ARM_ACCESSION', 'DISEASE_ONTOLOGY_ID',
       'DISEASE_PREFERRED', 'DISEASE_REPORTED', 'DISEASE_STAGE_PREFERRED',
       'DISEASE_STAGE_REPORTED', 'EXPOSURE_MATERIAL_ID',
       'EXPOSURE_MATERIAL_PREFERRED', 'EXPOSURE_MATERIAL_REPORTED',
       'EXPOSURE_PROCESS_PREFERRED', 'EXPOSURE_PROCESS_REPORTED',
       'SUBJECT_ACCESSION'],
      dtype='object')

In [23]:
pheno2.drop(columns=['EXPOSURE_ACCESSION', 'ARM_ACCESSION', 'DISEASE_ONTOLOGY_ID',
                     'DISEASE_REPORTED', 'DISEASE_STAGE_PREFERRED',
       'DISEASE_STAGE_REPORTED', 'EXPOSURE_MATERIAL_ID',
       'EXPOSURE_MATERIAL_PREFERRED', 'EXPOSURE_MATERIAL_REPORTED',
       'EXPOSURE_PROCESS_PREFERRED', 'EXPOSURE_PROCESS_REPORTED'], inplace=True)

In [24]:
pheno2.index = pheno2.SUBJECT_ACCESSION

In [25]:
pheno2.head()

                      DISEASE_PREFERRED SUBJECT_ACCESSION
SUBJECT_ACCESSION
SUB207729          rheumatoid arthritis         SUB207729
SUB207730          rheumatoid arthritis         SUB207730
SUB207731          rheumatoid arthritis         SUB207731
SUB207732          rheumatoid arthritis         SUB207732
SUB207733          rheumatoid arthritis         SUB207733

In [26]:
pheno.index = pheno.sample_id

In [27]:
pheno.head()

           sample_id  age            sex           tissue donor_id
sample_id
SUB207729  SUB207729   21  Not Specified  Synovial tissue      RA1
SUB207730  SUB207730   21  Not Specified  Synovial tissue      RA2
SUB207731  SUB207731   21  Not Specified  Synovial tissue      RA3
SUB207732  SUB207732   21  Not Specified  Synovial tissue      RA4
SUB207733  SUB207733   21  Not Specified  Synovial tissue      RA5

In [28]:
pheno3 = pheno.merge(pheno2, right_index=True, left_index=True)

In [29]:
pheno3

,sample_id,age,sex,tissue,donor_id,DISEASE_PREFERRED,SUBJECT_ACCESSION
SUB207729,SUB207729,21,Not Specified,Synovial tissue,RA1,rheumatoid arthritis,SUB207729
SUB207730,SUB207730,21,Not Specified,Synovial tissue,RA2,rheumatoid arthritis,SUB207730
SUB207731,SUB207731,21,Not Specified,Synovial tissue,RA3,rheumatoid arthritis,SUB207731
SUB207732,SUB207732,21,Not Specified,Synovial tissue,RA4,rheumatoid arthritis,SUB207732
SUB207733,SUB207733,21,Not Specified,Synovial tissue,RA5,rheumatoid arthritis,SUB207733
SUB207734,SUB207734,21,Not Specified,Synovial tissue,RA6,rheumatoid arthritis,SUB207734

In [30]:
np.unique(pheno3.DISEASE_PREFERRED)

array(['rheumatoid arthritis'], dtype=object)

In [31]:
pheno3.replace(to_replace='rheumatoid arthritis',
          value='Rheumatoid Arthritis',
          inplace=True)

In [32]:
pheno = pheno3
del pheno2
del pheno3
gc.collect()

187

In [33]:
pheno.reset_index(drop=True, inplace=True)

In [34]:
pheno.head()

,sample_id,age,sex,tissue,donor_id,DISEASE_PREFERRED,SUBJECT_ACCESSION
0,SUB207729,21,Not Specified,Synovial tissue,RA1,Rheumatoid Arthritis,SUB207729
1,SUB207730,21,Not Specified,Synovial tissue,RA2,Rheumatoid Arthritis,SUB207730
2,SUB207731,21,Not Specified,Synovial tissue,RA3,Rheumatoid Arthritis,SUB207731
3,SUB207732,21,Not Specified,Synovial tissue,RA4,Rheumatoid Arthritis,SUB207732
4,SUB207733,21,Not Specified,Synovial tissue,RA5,Rheumatoid Arthritis,SUB207733

##### Immune compartment

In [35]:
files = os.listdir(path)
failed = []

for i in range(pheno.shape[0]):
    samp = pheno.donor_id[i]
    print("Processing "+samp)
    if (samp not in files):
        failed.append(samp)
        continue
        
    adata = sc.read_10x_mtx(path+samp+"/output/Gene/filtered/")
    
    adata.obs["dataset_id"] = "SDY1599_Wei_2020"
    adata.obs["donor_id"] = pheno.donor_id[i]+"_"+pheno.sample_id[i]
    adata.obs["tissue"] = pheno.tissue[i]
    adata.obs["cell_source"] = pheno.tissue[i]
    adata.obs["disease"] = pheno.DISEASE_PREFERRED[i]
    adata.obs["development_stage"] = "Adult"
    adata.obs["age"] = pheno.age[i]
    adata.obs["sex"] = pheno.sex[i]
    
    if 'adata_conc' in locals():
        adata.var_names_make_unique()
        adata_conc.var_names_make_unique()
        adata_conc = sc.concat([adata,adata_conc], index_unique="-")
        
    else:
        adata_conc = adata
    
    del adata
    gc.collect()

    print(adata_conc.shape)

Processing RA1
(7505, 36601)
Processing RA2
(11974, 36601)
Processing RA3
(15090, 36601)
Processing RA4
(18803, 36601)
Processing RA5
(23017, 36601)
Processing RA6
(26472, 36601)

In [36]:
failed

[]

In [37]:
adata_conc.obs["disease"].value_counts()

Rheumatoid Arthritis    26472
Name: disease, dtype: int64

In [38]:
s_path = "/nfs/team205/bh14/Datasets/Remapped/raw_adata/"
adata_conc.write_h5ad(s_path+"Tissue_or_Nonimmune/SDY1599_Wei_2020_.h5ad")